### ISSUE TITLE
Remote ReproHack Test Drive Checklist

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack-hq#28]
### Questions to answer during test drive
    
- [ ] **What are the requirements for the platform?**
    - how many participants (50)
    - how many rooms / participants with room? 
    - can people chose where they "go"/ which room to use or are rooms assigned?
        - SSI CW20: They had separate rooms that folks accessed through separate links. That way people chose.
        - Write a script to output csv with assigned rooms according to selected papers.
           - folks can ask an administrator to move them if they want at any time.

- [ ] **Central admin**: Admin roles
   - presenter
     - slide share
  - facilitator
    - break out room assignment
    - chat monitoring & answering questions
  - chair
    - mute / unmute
    
   
    
- [ ] **Decide on platform:**
    - Zoom ? (RLadies account)
    - Blackboard? (Sheffield University account) 

### Agenda

- Welcome
- Intro to Zoom (3 mins) (any volunteers?)
- Ice breaker (split into rooms) (10 mins?)
- Introduction & tips for reviewing (20 mins)
- 1st talk (10-15)
- Select papers
- COFFEE BREAK
- Work on papers
- Regroup - get someone from each group to tell us a bit about their experiences.
- LUNCH BREAK
- talk 2
- Work on papers
- Regroup - get someone from each group to tell us a bit about their experiences.
- talk 3
- Final Words (any volunteers?)
