### ISSUE TITLE
Remote ReproHack Checklist

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack-hq#29]
- [ ] Contact potential speakers
  - [ ] Speakers confirmed
- [ ] Finalise Date. (Proposed May 14th)
- [ ] Provide details of the new event to Niki
- [ ] Update Paper list and repo with any new details
- [ ] Push for more papers
- [ ] **Run test run** (April 9th)
- [ ] Provide details of the platform and how to join to Niki
- [ ] Finalise approach to break out rooms
- [ ] Adapt the paper list for easier navigating of papers.

**Comment by annakrystalli** [comment]
### DRAFT Agenda

- Welcome
- Intro to Zoom (3 mins) (any volunteers?)
- Ice breaker (split into rooms) (10 mins?)
- Introduction & tips for reviewing (20 mins)
- 1st talk (10-15)
- Select papers
- COFFEE BREAK
- Work on papers
- Regroup - get someone from each group to tell us a bit about their experiences.
- LUNCH BREAK
- talk 2
- Work on papers
- Regroup - get someone from each group to tell us a bit about their experiences.
- talk 3
- Final Words (any volunteers?)

**Comment by annakrystalli** [comment]
Remote event registration page: https://n8cir.org.uk/events/remote-reprohack/

**Comment by DanielaGawehns** [comment]
https://twitter.com/mikemorrison/status/1242445150619607040?s=20
